sonar.projectKey=telecare
sonar.projectName=telecare
sonar.host.url=http://localhost:9000
sonar.login=sqa_180f1e5d9f9b8b00751e74019b4000c7453cd248

sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8
